# Importing the dataset into a dataframe

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk

import seaborn as sns

from sklearn.metrics import confusion_matrix
import sklearn.metrics as metrics
import sklearn.model_selection as ms
import sklearn.preprocessing as preprocess
from sklearn.model_selection import train_test_split
import pickle


In [ ]:
#batching
#mini batch gradients
#shuffle

In [2]:
# !pip install pyarabic
# !pip install langdetect
# !pip install nltk

# from langdetect import detect
# import pyarabic.araby as araby
# nltk.download("all")


In [3]:
dataset_folder_path="/home/youssef/AUC/Spring22/CSCE493002 - Machine Learning/project/datasets"
df = pd.read_csv(dataset_folder_path+'/freqEncoded.csv')
df.head()

label                                               freq
0      1  {'متز': 1, 'نوع': 1, 'ما': 1, 'نظف': 1, 'وقع':...
1      1  {'احد': 1, 'سبب': 1, 'نجح': 1, 'امر': 2, 'كل':...
2      1  {'هدف': 1, 'نقل': 1, 'صخب': 1, 'شرع': 1, 'قهر'...
3      1  {'خلص': 3, 'بدء': 1, 'الل': 1, 'بهر': 1, 'زي':...
4      1  {'ياس': 1, 'جزء': 2, 'لا': 2, 'دبي': 1, 'ندق':...

### Drop unecessary columns and neutral label

In [4]:
df_copy=df[(df['label']!= 0)]

In [5]:
df_copy.reset_index(inplace=True,drop=True)
df_copy["label"]=df_copy["label"].map({-1:0,1:1})
# df_copy[df_copy["label"]==-1].map() #=df_copy["label"].str.replace("-1","0")
df_copy

/home/youssef/.local/lib/python3.8/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)


label                                               freq
0          1  {'متز': 1, 'نوع': 1, 'ما': 1, 'نظف': 1, 'وقع':...
1          1  {'احد': 1, 'سبب': 1, 'نجح': 1, 'امر': 2, 'كل':...
2          1  {'هدف': 1, 'نقل': 1, 'صخب': 1, 'شرع': 1, 'قهر'...
3          1  {'خلص': 3, 'بدء': 1, 'الل': 1, 'بهر': 1, 'زي':...
4          1  {'ياس': 1, 'جزء': 2, 'لا': 2, 'دبي': 1, 'ندق':...
...      ...                                                ...
66661      0  {'عرفش': 1, 'ليه': 1, 'كنت': 1, 'كمل': 1, 'وهي...
66662      0  {'لا': 3, 'سحق': 1, 'يكون': 1, 'كنق': 1, 'لنه'...
66663      0  {'ضعف': 1, 'جدا': 1, 'ولم': 1, 'متع': 1, 'به':...
66664      0  {'ملة': 1, 'جدا': 1, 'حمد': 1, 'حسن': 1, 'علو'...
66665      0  {'لن': 1, 'رجع': 1, 'اله': 1, 'مرة': 1, 'خرى':...

[66666 rows x 2 columns]

In [6]:
# df_copy=pd.concat([df_copy.head(),df_copy.tail()]) #sampling 10 points for testing

# Unique Dictionary

In [7]:


def get_unique(df,colname):
  sentences_arr=df[colname].to_numpy() #convert df to np array
  words=' '.join(sentences_arr).split(' ') # join all strings into one string then splitting to get the words
  words=np.array(words) #convert to np array
  unique,counts = np.unique(words,return_counts=True)
  return unique, counts

def get_unique_dict(unique,counts):
  unique_dict=dict(zip(unique,counts))
  unique_dict=dict(sorted(unique_dict.items(), key=lambda item: item[1],reverse=True))
  return unique_dict
def remove_redundant_words(unique_dict):
  stop_words=['من','على','عن','في','فى','و','ان','هذا','او','كتب','...','.','','الى','فيه','انه','قبل','//','..','،',':',"؟",'/']
  for k, v in list(unique_dict.items()):
      if(unique_dict[k]<100 or k in stop_words):
        del unique_dict[k]

  return unique_dict



In [8]:
#df_copy= pd.read_csv('freqEncoded.csv')
#unique,counts=get_unique(df_copy,"normalized")
unique,counts=get_unique(df_copy,"freq")
unique_dict=get_unique_dict(unique,counts)
unique_dict=remove_redundant_words(unique_dict)

In [9]:
print("There are %d Unique words:"%len(unique_dict))
unique_dict

There are 2838 Unique words:


{'1,': 1724707,
 '2,': 254179,
 '3,': 66119,
 '1}': 65678,
 '4,': 24199,
 "'جدا':": 16799,
 "'لا':": 16265,
 "'ما':": 13117,
 "'كان':": 12325,
 "'كثر':": 11793,
 "'كل':": 11732,
 "'قرء':": 11569,
 "'وجد':": 11393,
 "'عمل':": 11385,
 "'لم':": 11313,
 "'وقع':": 10642,
 '5,': 10607,
 "'غير':": 10025,
 "'ندق':": 9294,
 "'بعد':": 9224,
 "'غرف':": 9145,
 "'جمل':": 8904,
 "'روي':": 8738,
 "'لكن':": 8616,
 "'مع':": 8561,
 "'حدث':": 8098,
 "'خدم':": 8077,
 "'نظف':": 7907,
 "'نفس':": 7907,
 "'علم':": 7804,
 "'جمع':": 7229,
 "'التي':": 7228,
 "'الل':": 7046,
 "'هو':": 6993,
 "'فكر':": 6918,
 "'شخص':": 6779,
 "'وحد':": 6686,
 "'قرب':": 6616,
 "'بعض':": 6601,
 "'عجب':": 6543,
 "'ولا':": 6436,
 "'كانت':": 6341,
 "'شكل':": 6282,
 "'عند':": 6199,
 "'كلم':": 6178,
 "'عرف':": 6123,
 "'اخر':": 5959,
 "'رءع':": 5934,
 "'حتى':": 5912,
 "'الا':": 5863,
 "'شيء':": 5851,
 "'قدم':": 5827,
 "'دخل':": 5779,
 "'بين':": 5671,
 "'هذه':": 5606,
 "'شعر':": 5586,
 '6,': 5534,
 "'سلب':": 5350,
 "'نظر':": 5258,
 "'الذي'

In [10]:
df_copy

label                                               freq
0          1  {'متز': 1, 'نوع': 1, 'ما': 1, 'نظف': 1, 'وقع':...
1          1  {'احد': 1, 'سبب': 1, 'نجح': 1, 'امر': 2, 'كل':...
2          1  {'هدف': 1, 'نقل': 1, 'صخب': 1, 'شرع': 1, 'قهر'...
3          1  {'خلص': 3, 'بدء': 1, 'الل': 1, 'بهر': 1, 'زي':...
4          1  {'ياس': 1, 'جزء': 2, 'لا': 2, 'دبي': 1, 'ندق':...
...      ...                                                ...
66661      0  {'عرفش': 1, 'ليه': 1, 'كنت': 1, 'كمل': 1, 'وهي...
66662      0  {'لا': 3, 'سحق': 1, 'يكون': 1, 'كنق': 1, 'لنه'...
66663      0  {'ضعف': 1, 'جدا': 1, 'ولم': 1, 'متع': 1, 'به':...
66664      0  {'ملة': 1, 'جدا': 1, 'حمد': 1, 'حسن': 1, 'علو'...
66665      0  {'لن': 1, 'رجع': 1, 'اله': 1, 'مرة': 1, 'خرى':...

[66666 rows x 2 columns]

# TF-IDF

In [11]:
import ast
#converting string dict to dict
df_copy['freq']=df_copy['freq'].apply(lambda x: ast.literal_eval(x))
print(type(df_copy.head()["freq"][0]))

<class 'dict'>


/home/youssef/.local/lib/python3.8/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)


In [12]:
#joined words into a sentence again to use sklearn model

df_copy["text"]=df_copy["freq"].apply(lambda freq_dict: ' '.join(list(freq_dict.keys())) )
df_copy

label                                               freq  \
0          1  {'متز': 1, 'نوع': 1, 'ما': 1, 'نظف': 1, 'وقع':...   
1          1  {'احد': 1, 'سبب': 1, 'نجح': 1, 'امر': 2, 'كل':...   
2          1  {'هدف': 1, 'نقل': 1, 'صخب': 1, 'شرع': 1, 'قهر'...   
3          1  {'خلص': 3, 'بدء': 1, 'الل': 1, 'بهر': 1, 'زي':...   
4          1  {'ياس': 1, 'جزء': 2, 'لا': 2, 'دبي': 1, 'ندق':...   
...      ...                                                ...   
66661      0  {'عرفش': 1, 'ليه': 1, 'كنت': 1, 'كمل': 1, 'وهي...   
66662      0  {'لا': 3, 'سحق': 1, 'يكون': 1, 'كنق': 1, 'لنه'...   
66663      0  {'ضعف': 1, 'جدا': 1, 'ولم': 1, 'متع': 1, 'به':...   
66664      0  {'ملة': 1, 'جدا': 1, 'حمد': 1, 'حسن': 1, 'علو'...   
66665      0  {'لن': 1, 'رجع': 1, 'اله': 1, 'مرة': 1, 'خرى':...   

                                                    text  
0                       متز نوع ما نظف وقع جهز شاطيء طعم  
1      احد سبب نجح امر كل شخص هذه دول عشق ترب نحن نحب...  
2      هدف نقل صخب شرع قهر هدء جبل شيش عرف حقق ما جرى...  
3      خلص بدء الل بهر زي فيل زرق حمد راد خطى رحل قرء...  
4                ياس جزء لا دبي ندق كامل خدم ريح نفس وجد  
...                                                  ...  
66661  عرفش ليه كنت كمل وهي مش عجب حدث بطء ممل روي اط...  
66662  لا سحق يكون كنق لنه سيء شي وجد خدم فطر صبح ستي...  
66663      ضعف جدا ولم متع به كل قصه سرد لحل شهد بدن فكر  
66664  ملة جدا حمد حسن علو فنن وصف عند دقق حد ثني قرء...  
66665  لن رجع اله مرة خرى قرب بحر كان قدم ولا وجد خدم...  

[66666 rows x 3 columns]

In [13]:
#Splitting data
x=df_copy['text']
y=np.expand_dims(df_copy['label'],axis=1)
X_train,X_test,Y_train, Y_test = train_test_split(x, y, test_size=0.3, random_state=1)
print("Train: " ,X_train.shape,Y_train.shape,"Test: ",(X_test.shape,Y_test.shape))

Train:  (46666,) (46666, 1) Test:  ((20000,), (20000, 1))


# TF-IDF

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer= TfidfVectorizer()
tf_x_train = vectorizer.fit_transform(X_train)
tf_x_test = vectorizer.transform(X_test)

In [15]:
print(tf_x_train[1000])

  (0, 3054)	0.399087852883007
  (0, 530)	0.34295341672047236
  (0, 1238)	0.3213888542967605
  (0, 3274)	0.27977113661028613
  (0, 3322)	0.3532507371589668
  (0, 2397)	0.3197743819705713
  (0, 3140)	0.23655315983481154
  (0, 1253)	0.19516641960193287
  (0, 1683)	0.3833121697914325
  (0, 3361)	0.17187081033107315
  (0, 2709)	0.15743661547652255
  (0, 2717)	0.1385857309095193


# Models Comparison

### Imports

In [16]:
from sklearn.tree import DecisionTreeClassifier 
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
#SVM
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
#NN
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import classification_report
import sklearn.model_selection as modsel
from sklearn.model_selection import GridSearchCV

In [17]:
scoring = ['precision_macro', 'recall_macro','f1_macro','accuracy'] #used for CV

In [18]:
def convert_scores_to_df(scores):
    df=pd.DataFrame(scores)
    df.drop(columns=['fit_time','score_time'],inplace=True)
    return df
def display_heatmap(y_test,pred):
    matrix=confusion_matrix(y_test,pred)
    sns.heatmap(matrix,annot=True)
def print_cv_scores(scores):
    scores_df=convert_scores_to_df(scores)
    print(scores_df)
    print("Means:-\n",scores_df.mean())

## Nerual Networks

In [246]:
class AdamOptimizer:
    def __init__(self,beta1,beta2,alpha,eps=10e-8):
#         self.params=params
#         self.n_iter=n_iter
        self.beta1=beta1
        self.beta2=beta2
        self.alpha=alpha
        self.eps=eps
        self.ms=[]
        self.vs=[]
        
    def reset_params(self,layers):
        self.ms=[ 
                  [np.zeros_like(layer.W,dtype=np.float64), np.zeros_like(layer.b,dtype=np.float64)] 
                  for layer in layers      
                 ]
        self.vs=[ 
                  [np.zeros_like(layer.W,dtype=np.float64), np.zeros_like(layer.b,dtype=np.float64)] 
                  for layer in layers      
                 ]
#         print("vs:",self.vs[0][0])
        
    def update(self,layers,N):
#         print(self.vs[0][0])
        for i in range(len(layers)):
#             print("i:",i)
#             print("vs part1: ",self.vs[i][0])
#             print("beta2:",self.beta2)
            self.ms[i][0]= self.beta1*self.ms[i][0]+(1.0-self.beta1)*layers[i].dW
            self.ms[i][1]= self.beta1*self.ms[i][1]+(1.0-self.beta1)*layers[i].db
            
#             print("before: vs of",i," = ", self.vs[i][0])
            self.vs[i][0]= self.beta2*self.vs[i][0]+(1.0-self.beta2)*np.square(layers[i].dW)
            self.vs[i][1]= self.beta2*self.vs[i][1]+(1.0-self.beta2)*np.square(layers[i].db)
#             print("after: vs of",i," = ", self.vs[i][0])

#             print("vs:",self.vs[i][0])
#             print("eps:", self.eps)
            denDW= np.sqrt((self.vs[i][0] + self.eps))
            denB=(np.sqrt((self.vs[i][1] + self.eps)))
            
            numDW=(-1 * self.alpha * self.ms[i][0])
            numB=(-1 * self.alpha * self.ms[i][1])
                    
            deltaW = np.array(numDW /denDW ,dtype=np.float64)
            deltab = np.array( numB/ denB  ,dtype=np.float64)
        
#             print("deltaW",deltaW)
#             print("deltab",deltab)
            layers[i].W +=  deltaW/np.sqrt(N)
            layers[i].b +=  deltab/np.sqrt(N)
        
# class GradientDescent:
#     def __init__(self,alpha):
#         self.alpha=alpha
#     def reset_params(self,layers):
#         pass
#     def update(self,layers,N):
#         for i in range(len(layers)):
#             # layers[i].dW=layers[i].dW/N
#             # layers[i].db=layers[i].db/N
#             layers[i].W = layers[i].W - self.alpha * (layers[i].dW/N)
#             layers[i].b = layers[i].b - self.alpha * (layers[i].db/N)

In [247]:
import numpy as np
import pickle


class Layer:
    
    ### activations
    def _relu(self,z):
        return np.maximum(0,z)
    def _diff_relu(self,z):
        dZ=np.array(z,copy=True)
        dZ[dZ<=0]=0
        dZ[dZ>0]=1
        return dZ
    
    def _identity(self,z):
        return z
    
    def _identity_diff(self,z):
        return np.ones_like(z)
    
    def _sigmoid(self,z):
        return (1/(1+np.exp(-1*z)))

    def _diff_sigmoid(self,z):
        return self._sigmoid(z)*(1-self._sigmoid(z))
    
    def _softmax(self,z):
        expZ= np.exp(z-np.max(z))
        return expZ/expZ.sum(axis=0, keepdims=True)
    def _diff_softmax(self,z):
        pass

    
    ###########

    def __init__(self,n_input,n_output, activation="identity",name=None):
        self.n_output= n_output
        self.n_input= n_input
        self.name= name
        
        if activation == "identity":
            self.activation = self._identity
            self.diff_act= self._identity_diff
        
        elif activation == "sigmoid":
            self.activation = self._sigmoid
            self.diff_act= self._diff_sigmoid
            
        elif activation == "softmax":
            self.activation=self._softmax
            self.diff_act=self._diff_softmax
        elif activation =="relu":
            self.activation=self._relu
            self.diff_act=self._diff_relu
        
            
        
        
        self.W= np.random.randn(self.n_output,self.n_input)*np.sqrt(2/self.n_input)
        self.b= np.random.randn(self.n_output,1)*np.sqrt(2/self.n_input)

        self.dW= np.zeros_like(self.W)
        self.db= np.zeros_like(self.b)
        
        self.Z= None
        self.Ai = None
    def print_shapes(self):
        print("W: ",self.W.shape)
        print("b: ",self.b.shape)
    
    def forward(self,Ai): #data dim 

        z =  np.add((self.W @ Ai),self.b)
        A = self.activation(z)

        
        self.Z = z
        self.Ai = Ai
        return A
    
    
    def backward(self,inp):
        
#         print("input shape: ",end='')
#         print(inp.shape)
       
        act_diff = self.diff_act(self.Z)
#         print("act_diff shape: ",end='')
#         print(act_diff.shape)
        
        tmp = inp * act_diff
#         print("tmp shape: ",end='')
#         print(tmp.shape)
        
        bet = tmp @ self.Ai.T # vector of 1s
#         print("bet shape: ",end='')
#         print(bet.shape)
        
        
        e = np.ones((self.Ai.shape[1],1))
        db = tmp @ e
#         print("db shape: ",end='')
#         print(db.shape)
        self.dW = (self.dW + bet)
#         print("dw:",self.dW.shape,"\nlen:",len(self.dW))
        self.db = self.db + db
        
        
        return self.W.T @ tmp
    
    def print_weights(self):
        print("\n###################")
        if(self.name):
            print("name: ",self.name)
        print("dW: ",self.dW, "W: ",self.W)
    
    def zeroing_delta(self):
        self.dW= np.zeros_like(self.W)
        self.db= np.zeros_like(self.b)


class NN:
    
    ########
    ## losses
    def _MSE(self,y,yhat):
        a=np.square(yhat-y)
        a=np.sum(a)
        b= 1/(2*y.shape[1])
        return a*b

    ## diff losses
    def _diff_MSE(self,y,yhat,X):
        return (yhat-y)
    
    def _binary_cross_entropy(self,y,yhat):
#         print("inside bin cross entropy\n")
        arr= -(y*np.log(yhat)+(1-y)*np.log(1-yhat))
#         print("arr:",arr)
        return arr.mean()
        
    def _diff_binary_cross_entropy(self,y,yhat,X):
#         print("X shape: ",X.shape)
#         print("y shape: ",y.shape)
#         print("y hat shape: ",yhat.shape)
        dl_dyhat= -(y/yhat - (1-y)/(1-yhat))
#         loss= X.T @ (yhat - y)
#         print("dl_dyhat:",dl_dyhat)
        return dl_dyhat
    
    #########
    
    def __init__(self,optimizer,loss="binary_cross"):
        self.layers = []
        self.optimizer=optimizer
        self.loss_name=loss
        self.initialize_loss();
    
   
    def initialize_loss(self): 
        if(self.loss_name=="binary_cross"):
            self.loss=self._binary_cross_entropy
            self.loss_diff=self._diff_binary_cross_entropy
        elif self.loss_name=="MSE":
            self.loss=self._MSE
            self.loss_diff=self._diff_MSE
        
    
 
    
    def forward(self,x_train):
        a=x_train
        for layer in self.layers:
            a = layer.forward(a)
        return a
    
    def backward(self,input):
        gd = input
        for layer in self.layers[::-1]:
            gd = layer.backward(gd)
            
    def add_layer(self,n_input,n_output, activation="identity",name=None):
        self.layers.append(Layer(n_input,n_output, activation=activation,name=name))
        
    def fit(self, x_train,y_train, epochs=5): #data dim is MxN .. M no of examples.. N no of dimension
        
        M = x_train.shape[0]
        
        
        x_train = x_train.T
        y_train = y_train.T
        
        self.optimizer.reset_params(self.layers)
        
        for i in range(epochs):
            print("Epoche {}/{}".format(i+1,epochs))
            y_hat= self.forward(x_train)
            
            dl_dyhat = self.loss_diff(y_train,y_hat,self.layers[-1].Ai)
            loss=self.loss(y_train,y_hat)
            print("loss=",loss)

            
            self.backward(dl_dyhat)
#             print("Before update vs=",self.optimizer.vs[0][0])
            self.optimizer.update(self.layers,M)
#             self.print_weights()
            
            # zeroing deltas
            for layer in self.layers:
                layer.zeroing_delta()
            
        print("Finished....") 
            
            
        

    
    def predict(self,x_test): #data dim is NxD .. N no of examples.. D no of dimension
        print("x_test:", x_test.shape)
        y_hat= self.forward(x_test.T).T
        return y_hat
#         print(y_hat)
#         y_hat[y_hat>0.5]=1
#         y_hat[y_hat<=0.5]=0
#         return y_hat
                    
    def print_weights(self):
        for i in range(len(self.layers)):
            print("layer i= ",i,end=" ")
            self.layers[i].print_weights()
    def print_shapes(self):
        for layer in self.layers:
            layer.print_shapes()
    
    def save_model(self,path):
        model=[self.layers,self.optimizer,self.loss]

        file=open(path,"wb")
        print("dumped model: ",model)

        pickle.dump(model,file)

        file.close()

    def load_model(self,path):
        file=open(path,"rb")

        model=pickle.load(file)

        file.close()
        print("loaded model: ",model)
        
        self.layers,self.optimizer,self.loss=model
        self.initialize_loss()

    

In [248]:
print(tf_x_train.shape)
print(tf_x_test.shape)
Y_train.reshape(Y_train.shape[0],1)
print(Y_train.shape)
print(Y_test.shape)

(46666, 3593)
(20000, 3593)
(46666, 1)
(20000, 1)


In [249]:

adam= AdamOptimizer(beta1 = 0.9,beta2 = 0.99,alpha=1,eps=0.001)
nn = NN(loss="binary_cross",optimizer=adam)

nn.add_layer(tf_x_train.shape[1],64,activation="relu",name="l1")
nn.add_layer(64,32,activation = "relu",name="l2")
# nn.add_layer(32,16,activation = "relu",name="l3")
nn.add_layer(32,8,activation = "relu",name="l4")
nn.add_layer(8,1,activation = "sigmoid",name="l5")



In [250]:
tf_x_train.shape

(46666, 3593)

In [251]:
# adam.reset_params(nn.layers)

In [254]:
nn.fit(tf_x_train,Y_train,1)

Epoche 1/1
loss= 0.04770385741062807
Finished....


In [255]:
y_pred=nn.predict(tf_x_test)

x_test: (20000, 3593)


In [256]:
len(y_pred)

20000

In [260]:
# print(min(y_pred))
# max(y_pred)
np.unique(y_pred)
y2=y_pred[y_pred<0.5]

print(min(y_pred),max(y_pred))
y2

[3.86296473e-11] [0.9999998]


array([1.87932660e-01, 2.15720835e-02, 6.25458706e-02, ...,
       4.00375760e-03, 2.80340283e-06, 6.39030687e-03])

In [259]:
y3= y_pred[y_pred>=0.5]


array([0.99863292, 0.96466802, 0.99902475, ..., 0.99972351, 0.96872718,
       0.99988759])

In [261]:
y4=y_pred.copy()
y4[y4>=0.5]=1
y4[y4<0.5]=0
np.unique(y4,return_counts=True)

(array([0., 1.]), array([ 6538, 13462]))

In [66]:
nn.save_model("modelDump.joblib")

dumped model:  [[<__main__.Layer object at 0x7f8c78b23640>, <__main__.Layer object at 0x7f8c78c1af40>, <__main__.Layer object at 0x7f8c78c1a400>, <__main__.Layer object at 0x7f8c8456c670>], <__main__.AdamOptimizer object at 0x7f8c78b23e20>]


In [68]:
loadedNN= NN(lr=0.01,loss="binary_cross",optimizer=adam)
loadedNN.load_model("modelDump.joblib")

loaded model:  [[<__main__.Layer object at 0x7f8c78c01640>, <__main__.Layer object at 0x7f8c78a3de20>, <__main__.Layer object at 0x7f8c78a3d1c0>, <__main__.Layer object at 0x7f8c78a3d580>], <__main__.AdamOptimizer object at 0x7f8c7a573730>]


In [69]:
loadedNN.print_weights()

layer i=  0 
###################
name:  l1
dW:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] W:  [[ 0.09329637  0.0219642   0.14563274 ... -0.08334918 -0.11055184
  -0.17838875]
 [ 0.06012486 -0.07319563  0.13958616 ...  0.037964   -0.07443076
  -0.02376223]
 [ 0.07058842 -0.02897183  0.16069103 ... -0.07785164 -0.09886404
   0.10261401]
 ...
 [-0.00928848 -0.04190254  0.01456637 ...  0.03001082  0.05063087
   0.08264691]
 [-0.14007669 -0.03305241  0.08963179 ...  0.00556524  0.00100418
   0.04729674]
 [-0.21262609  0.08992008 -0.01326203 ... -0.0193908  -0.06945065
  -0.0300281 ]]
layer i=  1 
###################
name:  l2
dW:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] W:  [[-0.20247318 -0.02339464  0.13343745 ... -0.04334661  0.10004348
   0.00333405]
 [ 0.178748

In [47]:
from joblib import dump, load
# dump=pickle.dumps(nn)
dump(nn,"out.pckl")

['out.pckl']

In [51]:
loadedCLF=load("out.pckl")
y_pred2=loadedCLF.predict(tf_x_test)
y_pred2
print("hello")

[[0.20683907]
 [0.22103681]
 [0.22143776]]
hello


In [262]:

from sklearn.metrics import confusion_matrix
import sklearn.metrics as metrics
import sklearn.model_selection as ms
import sklearn.preprocessing as preprocess
from sklearn.model_selection import train_test_split

In [263]:
# Y_test
print(classification_report(y4,Y_test))


              precision    recall  f1-score   support

         0.0       0.60      0.90      0.72      6538
         1.0       0.94      0.71      0.81     13462

    accuracy                           0.77     20000
   macro avg       0.77      0.81      0.77     20000
weighted avg       0.83      0.77      0.78     20000



In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import numpy as np
import pandas as pd
import math
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import os

tf_list= pd.read_csv('/first.txt')
array_tf_list = np.array(tf_list)
test_list=pd.read_csv('/second.txt')
array_test_list = np.array(test_list)
tlabels= pd.read_csv('/third.txt')
array_tlabels= np.array(tlabels)

label_test=pd.read_csv('/fourth.txt')
arr_lt= np.array(label_test)
array_tf_list=np.reshape(array_tf_list,[256,5999])
train_label_onehot =np.zeros((10,5999))
for i in range(6000-1):
  value=array_tlabels[i]
  for row in range (1,10,1):
    if (value==row):
      train_label_onehot[value,i]=1

def sigmoid(Z):
    A = 1/(1+np.exp(-Z))
    cache = Z
    return A, cache

def relu(Z):
    A = np.maximum(0,Z)
    cache = Z
    return A, cache

def softmax(Z):
    e_x = np.exp(Z)
    A= e_x / np.sum(np.exp(Z))
    cache=Z
    return A,cache

def relu_backward(dA, cache):
    Z = cache
    dZ = np.array(dA, copy=True)
    dZ[Z <= 0] = 0
    assert (dZ.shape == Z.shape)
    return dZ

def sigmoid_backward(dA, cache):
    Z = cache
    s = 1/(1+np.exp(-Z))
    dZ = dA * s * (1-s)
    assert (dZ.shape == Z.shape)
    return dZ

def softmax_backward(Z,cache):
    Z=cache
    length=10
    dZ=np.zeros((6000-1,10))
    Z=np.transpose(Z)
    for row in range (0,5999):
            den=(np.sum(np.exp(Z[row,:])))*(np.sum(np.exp(Z[row,:])))
            for col in range (0,10):
                sums=0
                for j in range (0,10):
                    if (j!=col):
                        sums=sums+(math.exp(Z[row,j]))

                dZ[row,col]=(math.exp(Z[row,col])*sums)/den
    dZ=np.transpose(dZ)
    Z=np.transpose(Z)
    assert (dZ.shape == Z.shape)
    return dZ

def initialize_parameters_deep(mylay_dimensions):
    parameters = {}
    L = len(mylay_dimensions)
    for l in range(1, L):
        parameters['W' + str(l)] = np.random.randn(mylay_dimensions[l], mylay_dimensions[l-1]) / np.sqrt(mylay_dimensions[l-1]) #*0.01
        parameters['b' + str(l)] = np.zeros((mylay_dimensions[l], 1))
    return parameters

def for_front(A, W, b):
    Z = np.dot(W,A) +b
    cache = (A, W, b)
    assert(Z.shape == (W.shape[0], A.shape[1]))
    return Z, cache

def for_active(A_prev, W, b, activation):
    if activation == "sigmoid":
        Z, linear_cache = for_front(A_prev, W, b)
        A, activation_cache = sigmoid(Z)
    elif activation == "relu":
        Z, linear_cache = for_front(A_prev, W, b)
        A, activation_cache = relu(Z)
    elif activation == "softmax":
        Z, linear_cache = for_front(A_prev, W, b)
        A, activation_cache = softmax(Z)
    cache = (linear_cache, activation_cache)
    return A, cache

def my_mod_for(X, parameters):
    caches = []
    A = X
    L = len(parameters)
    for l in range(1, L):
        A_prev = A
        A, cache = for_active(A_prev, parameters['W' + str(l)], parameters['b' + str(l)], activation = "relu")
        caches.append(cache)
    AL, cache = for_active(A, parameters['W' + str(L)], parameters['b' + str(L)], activation = "softmax")
    caches.append(cache)
    return AL, caches

def calc_cost(AL, Y):
    m = Y.shape[1]
    cost = (-1 / m) * np.sum(np.multiply(Y, np.log(AL)) + np.multiply(1 - Y, np.log(1 - AL)))
    return cost

def linear_backward(dZ, cache):
    A_prev, W, b = cache
    m = A_prev.shape[1]
    dW = 1./m * np.dot(dZ,A_prev.T)
    db = (1/m)*np.sum(dZ, axis=1, keepdims=True);
    dA_prev = np.dot(W.T,dZ)
    return dA_prev, dW, db

def lin_back(dA, cache, activation):
    linear_cache, activation_cache = cache
    if activation == "relu":
        dZ = relu_backward(dA, activation_cache)
        dA_prev, dW, db = linear_backward(dZ, linear_cache)
    elif activation == "sigmoid":
        dZ = sigmoid_backward(dA, activation_cache)
        dA_prev, dW, db = linear_backward(dZ, linear_cache)
    elif activation == "softmax":
        dZ = softmax_backward(dA, activation_cache)
        dA_prev, dW, db = linear_backward(dZ, linear_cache)
    return dA_prev, dW, db

def my_mod_back(AL, Y, caches):
    arbit_arr = {}
    L = len(caches)
    dAL = - (np.divide(Y, AL) - np.divide(1 - Y, 1 - AL))
    M=len(my_network_dimensions)
    current_cache = caches[M-2]
    arbit_arr["dA"+str(M-1)], arbit_arr["dW"+str(M-1)], arbit_arr["db"+str(M-1)] = lin_back(dAL, current_cache, activation = "softmax")#M-1
    for l in reversed(range(L-1)):
        current_cache = caches[l]
        dA_prev_temp, dW_temp, db_temp = lin_back(arbit_arr["dA" + str(l + 2)], current_cache, activation = "relu")
        arbit_arr["dA" + str(l + 1)] = dA_prev_temp
        arbit_arr["dW" + str(l + 1)] = dW_temp
        arbit_arr["db" + str(l + 1)] = db_temp
    return arbit_arr

def change_weights(parameters, arbit_arr, learning_rate):
    for l in range(len_update-1):
        parameters["W" + str(l+1)] =parameters["W" + str(l+1)] - (learning_rate*arbit_arr["dW" + str(l+1)])
        parameters["b" + str(l+1)] = parameters["b" + str(l+1)] - (learning_rate*arbit_arr["db" + str(l+1)])
    return parameters

def plot_graph(cost_plot):
    x_value=list(range(1,len(cost_plot)+1))
    plt.xlabel('iteration')
    plt.ylabel('cost')
    plt.plot(x_value,cost_plot,0.,color='g')
my_network_dimensions = [256,150,100,50,10]
len_update=len(my_network_dimensions)
def my_lay_mod(X, Y, my_network_dimensions, learning_rate , num_iterations , print_cost=False):#lr was 0.009
    costs = []
    cost_plot=np.zeros(num_iterations)
    parameters = initialize_parameters_deep(my_network_dimensions)
    for i in range(0, num_iterations):
        AL, caches = my_mod_for(X, parameters)
        cost =calc_cost(AL, Y)
        arbit_arr = my_mod_back(AL, Y, caches)
        parameters = change_weights(parameters, arbit_arr, learning_rate)
        cost_plot[i]=cost;
    plot_graph(cost_plot)
    return parameters
parameters = my_lay_mod(array_tf_list, train_label_onehot, my_network_dimensions,learning_rate = 0.005, num_iterations =50 , print_cost = True)
for weight in parameters:
    print(weight)